name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - uat
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Deploy to GitHub Pages (DEV)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: dev

  deploy-uat:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/uat'

    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Deploy to GitHub Pages (UAT)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: uat

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Deploy to GitHub Pages (PROD)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
